### ISSUE TITLE
How to remove tags ?

### ISSUE THREAD

**Issue by anjosc** [greenfrvr/hashtag-view#10]
There is no method to remove a tag (or add a single tag, btw), so I tried calling setData with a new Array, and calling invalidate, which works.
However, removing the last tag by setting an empty array, crashes with 
"java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first."
As workaround, I'm just setting visibility to GONE whenever I remove all tags.
Is there a recommended way to remove one or all tags ?

**Comment by greenfrvr** [comment]
Sorry but this features aren't supported yet. Currently I'm working on dynamically adding/removing items. Also I know about the problem when setting empty array as a data. I guess that all will be implemented in v1.3.0.

**Comment by jd-alexander** [comment]
When will this feature be released? It's the only thing stopping me from using this library.

**Comment by greenfrvr** [comment]
Sorry for such a long pause. Here is the situation, I have implemented capability of dynamically adding/removing items. It doesn't use some beautiful animations or transitions, but it works clean and simple. Almost sure next release will be on this week.

**Comment by jd-alexander** [comment]
awesome :+1:
