### ISSUE TITLE
If more tag the app is no responsed

### ISSUE THREAD

**Issue by phamthangnd** [greenfrvr/hashtag-view#11]
if we had more 200 tags, the app is no response.

**Comment by greenfrvr** [comment]
are you sure that the problem is in amount of items? can you please tell some more information to help me investigate this issue?

**Comment by phamthangnd** [comment]
In sample app, if you add more tag string (>200-300 tags), device is no response.
BaseFragments, String[] DATA  length >300 this is appeared.
Tested on Samsung Note 3, Samsung S5

Here my captured screen:
![no response](https://cloud.githubusercontent.com/assets/12743336/10720951/1e83cf52-7bcf-11e5-8253-8247795b2b44.png)
![sampledata](https://cloud.githubusercontent.com/assets/12743336/10720953/1e85cf6e-7bcf-11e5-8b67-4faa0484786a.png)
![device-2015-10-26-104419](https://cloud.githubusercontent.com/assets/12743336/10720952/1e852050-7bcf-11e5-94fb-2248ea59c8e2.png)

**Comment by martinzarzar** [comment]
So with 100 items.
Detail code :

```
List<String> items = new ArrayList<>();
        for(int i = 0; i <= 100; i++) {
            items.add("#HashTag"+i);
        }
        hashtagView2.setData(items,new HashtagView.DataTransform<String>() {
            @Override
            public CharSequence prepare(String item) {
                SpannableString spannableString = new SpannableString("#" + item);
                spannableString.setSpan(new ForegroundColorSpan(Color.parseColor("#FF0000")), 0, 1, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);
                return spannableString;
            }
        });
    }
```

![tag](https://cloud.githubusercontent.com/assets/4175950/10852154/694e4338-7f16-11e5-94e5-4d5ba06442a7.png)

**Comment by greenfrvr** [comment]
Thanks guys. As an intermediate result of my investigation I got that the problem is not connected to the amount of items. It's more like layout positioning issue, some problem with sorting algorythm. Still working on it. Will try to fix on weekend and release new version.

**Comment by martinzarzar** [comment]
Thanks @greenfrvr !

**Comment by yankeppey** [comment]
The temporary simple solution. It doesn't use "smart" positioning of tags, but it works. MutableInt from commons-lans (http://grepcode.com/file_/repo1.maven.org/maven2/commons-lang/commons-lang/2.3/org/apache/commons/lang/mutable/MutableInt.java/?v=source) is used.  `nosort()` method should be called instead of `sort()`.

```
private int evaluateRowsQuantityNoSort() {
    if (widthList == null || widthList.isEmpty()) return 0;

    int rows = (int) Math.ceil(totalItemsWidth / getViewWidth());
    ArrayList<MutableInt> rowsWidth = new ArrayList<>(rows);
    for (Float item : widthList) {
        boolean inserted = false;
        for (int i = 0; i < rowsWidth.size(); i++) {
            if (rowsWidth.get(i).intValue() + item <= getViewWidth()) {
                inserted = true;
                rowsWidth.get(i).add(item);
            }
        }
        if (!inserted) {
            rowsWidth.add(new MutableInt(item.intValue()));
        }

    }
    return rowsWidth.size();
}

private void nosort() {
    if (data == null || data.isEmpty()) return;

    int rowsQuantity = rowCount == 0 ? evaluateRowsQuantityNoSort() : rowCount;
    int[] rowsWidth = new int[rowsQuantity];

    viewMap = ArrayListMultimap.create(rowsQuantity, data.size());

    for (ItemData item : data) {
        for (int i = 0; i < rowsQuantity; i++) {
            if (rowCount > 0 || rowsWidth[i] + item.width <= getViewWidth()) {
                rowsWidth[i] += item.width;
                viewMap.put(i, item);
                break;
            }
        }
    }
}
```
