### ISSUE TITLE
Gradle doesn't build (likely due to this being very out of date)

### ISSUE THREAD

**Issue by djhacktor** [greenfrvr/hashtag-view#12]
Error:Execution failed for task ':app:dexDebug'.

com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by greenfrvr** [comment]
I don't really get this issue. Are you sure that's problem of my library? If so can you please provide some more information to help me investigate it.
