### ISSUE TITLE
library doesn't let use selector in tagTextColor attrribute 

### ISSUE THREAD

**Issue by yankeppey** [greenfrvr/hashtag-view#13]
Hi, 
first of all, thank you for your library.
Unfortunately it doesn't let user to use color selectors in tagTextColor attribute. In my app I need to change text color depending on is tag selected or not (because the background changes significantly as well).
Is there any special reason for it?
The implementation is very simple:

```
private void extractAttributes(AttributeSet attrs) {
    //...
    itemTextColorStateList = a.getColorStateList(R.styleable.HashtagView_tagTextColor);
    //...  
}

private void decorateItemTextView(TextView textView) {
    //textView.setTextColor(itemTextColor);
    textView.setTextColor(itemTextColorStateList);
    //...
}
```

Or do I miss any point?

**Comment by greenfrvr** [comment]
sorry for keeping waiting, I have already implemented color state list support and will add this to next release (almost sure it's gonna be this week)
