### ISSUE TITLE
Make items show in alphabetically order

### ISSUE THREAD

**Issue by zunjae** [greenfrvr/hashtag-view#22]
Is there a reason why the item order changes (except for your algorithm)?

I'm trying to display some names but the order keeps changing every time I rotate my phone

**Comment by ankesh4040** [comment]
@zunjae Did you find any way out to show items in alphabetical order

**Comment by zunjae** [comment]
Unfortunately not. I'll probably look into a different library

**Comment by greenfrvr** [comment]
Implemented different compose modes in v1.3.0. Original and linear. Original is the same as in previous versions. Linear compose mode will save order of incoming data.
