### ISSUE TITLE
Unable to retrieve all tags from hashtagview

### ISSUE THREAD

**Issue by Renk01** [greenfrvr/hashtag-view#28]
Hi,
probably I am missing something. If so, I am sorry. But I am not able to retrieve all entered tags from the hashtagview programmatically. I didn´t find any method to get that information. And in the documentation of the library it´s also not described how to get all tags.

P.S.: Appart from that problem this library is just awesome. Thanks for the work and effort you put into this.

**Comment by icodeyou** [comment]
Same !

**Comment by greenfrvr** [comment]
@Renk01 @jeanvallon added method in v1.3.0
